#!/bin/bash
#PBS -r n
##PBS -q mediummem
#PBS -m e
#PBS -M bxia@houstonmethodist.org
#PBS -l walltime=96:00:00
#PBS -l nodes=1:ppn=1
##PBS -l pmem=16000mb

cd /home/tmhbxx3/archive/H3K4me3/GEO_with_input/NRF

module load python/2.7.11

python ./NRF.py


['ENCFF048ZOQ_ENCFF827YXC.fastq',  'ENCFF716YLE_ENCFF665BBC.fastq',  'ENCFF853HFC_ENCFF398JCG.fastq',
'ENCFF163PYU_ENCFF486LTO.fastq',  'ENCFF768AIX_ENCFF694EZB.fastq',  'ENCFF878ZLP_ENCFF269SMY.fastq',
'ENCFF584YEG_ENCFF802LTL.fastq',  'ENCFF794IID_ENCFF102BFB.fastq']
